### ISSUE TITLE
Bugs: hide and seek

### ISSUE THREAD

**Issue by JustoRago** [Kevo-hacker/Desktop-Version-Portfolio#11]
I found the following bugs:

- Missing argument expression in the .addEventListener, line 174. Among other things it somehow caused the entire javascript to not show up as a part of the page, I had to fix it first to be able to debug.
- Missing plus sign in the assignment, line 79. It made it so only the last element in the technologies array in the card objects got passed as a list item.
- Typo in line 189, the correct id is 'email'. Input from the email input area is was not registered.
- Typo in line 171, the correct id is 'message_error'. Prevented the error message from appearing.

**Comment by Kelvin-Ben** [comment]
## Hey @asdt560, 
- you did very well to find a few bugs I had introduced in the code
- It was great experience to find a few that i had introduced and showing you the others
- I hope you continue to keep the same motivation to improve your skills even more
