### ISSUE TITLE
Project review

### ISSUE THREAD

**Issue by MAHDIA001** [Kevo-hacker/Desktop-Version-Portfolio#7]
Nice job Benjamin!
You have done it very well.
your code is very clean and the class names are very specific.
Keep it up

**Comment by Kelvin-Ben** [comment]
> Nice job Benjamin! You have done it very well. your code is very clean and the class names are very specific. Keep it up

thank you @MAHDIA001

**Comment by vvoo21** [comment]
Hi @Kelvin-Ben , 
Good usage of semantic elements. 
Well-structured HTML document.
Good usage of JavaScript!!

**Comment by Kelvin-Ben** [comment]
> Hi @Kelvin-Ben, Good usage of semantic elements. Well-structured HTML document. Good usage of JavaScript!!

Thank you @vvoo21
