### ISSUE TITLE
Microverse: Peer to peer code-review

### ISSUE THREAD

**Issue by Javivy** [Kevo-hacker/Desktop-Version-Portfolio#8]
Hi, @Kelvin-Ben great job so far! But there are a few things you can still improve :))

  - Kindly Add the live server for your project in the readme file
  - Please name your files more adequately, i.e. Your JavaScript file is named navbar, try to name it with something more generical

**Comment by Kelvin-Ben** [comment]
> Hi, @Kelvin-Ben great job so far! But there are a few things you can still improve :))
> 
> * Kindly Add the live server for your project in the readme file
> * Please name your files more adequately, i.e. Your JavaScript file is named navbar, try to name it with something more generical

Thank you @Javivy, I will make this changes
